//users
export const LOG_OUT="LOG_OUT";
export const LOG_IN="LOG_IN";
export const SIGN_IN="SIGN_IN";
//enter or go out from private region
export const CHANGE_USER_LOCATION="CHANGE_USER_LOCATION";

//attractions
export const SAVE_ATTRACTIONS="SAVE_ATTRACTIONS";
export const SAVE_LOVED_ATTRACTIONS="SAVE_LOVED_ATTRACTIONS";
export const ADD_ATTRACTION="ADD_ATTRACTION";
export const DELETE_ATTRACTION="DELETE_ATTRACTION";
export const UPDATE_ATTRACTION="UPDATE_ATTRACTION";
export const SELECT_ATTRACTION="SELECT_ATTRACTION";
export const UPDATE_FILTERING="UPDATE_FILTERING";
export const CHANGE_SWITCH="CHANGE_SWITCH";
export const ADD_LOVED_ATTRACION="ADD_LOVED_ATTRACION";
export const REMOVE_LOVED_ATTRACION="REMOVE_LOVED_ATTRACION";

//items
export const ADD_ITEM="ADD_ITEM";
export const REMOVE_ITEM_FROM_MY_LIST="REMOVE_ITEM_FROM_MY_LIST";
export const ADD_ITEM_TO_MY_LIST="ADD_ITEM_TO_MY_LIST";
export const REMOVE_ITEM="REMOVE_ITEM";
export const UPDATE_ITEMS_SELECTED="UPDATE_ITEMS_SELECTED";
export const SAVE_ITEMS = "SAVE_ITEMS";
export const SAVE_ITEMS_SELECTED = "SAVE_ITEMS_SELECTED";
export const SAVE_PRODUCT_TYPES = "SAVE_PRODUCT_TYPES";
export const SAVE_STORAGE_TYPES = "SAVE_STORAGE_TYPES";

//lists
export const SAVE_TRIP_LIST = "SAVE_TRIP_LIST";
export const SAVE_ATTRACTION_LIST_ID = "SAVE_ATTRACTION_LIST_ID";

